### ISSUE TITLE
__invoke(): Argument #1 ($record) must be of type array, Monolog\LogRecord given on PHP 8.1/SF 6.2

### ISSUE THREAD

**Issue by jonthekiller** [auxmoney/OpentracingBundle-Monolog#23]
I test the bundle on Symfony 6.2 and PHP 8.1 and the cache:clear crash with the following error:

`Auxmoney\OpentracingMonologBundle\Processor\MonologTracingHeaderProcessor::__invoke(): Argument #1 ($record) must be of type array, Monolog\LogRecord given, called in /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php on line 352`

If I make the following quick change in the file /var/www/html/vendor/auxmoney/opentracing-bundle-monolog/Processor/MonologTracingHeaderProcessor.php it works:

```<?php

declare(strict_types=1);

namespace Auxmoney\OpentracingMonologBundle\Processor;

use Auxmoney\OpentracingBundle\Internal\Opentracing;

use Monolog\LogRecord;

use const OpenTracing\Formats\TEXT_MAP;

final class MonologTracingHeaderProcessor
{
    private Opentracing $opentracing;

    public function __construct(Opentracing $opentracing)
    {
        $this->opentracing = $opentracing;
    }

    /**
     * @param LogRecord<string,mixed> $record
     * @return LogRecord<string,mixed>
     */
    public function __invoke(LogRecord $record): LogRecord
    {
        $span = $this->opentracing->getTracerInstance()->getActiveSpan();
        if ($span) {
            $context = [];
            $this->opentracing->getTracerInstance()->inject(
                $span->getContext(),
                TEXT_MAP,
                $context
            );
            $record['extra']['opentracing-context'] = json_encode($context);
        }
        return $record;
    }
}
```

Not sure if it's the best fix.

**Comment by cawolf** [comment]
Hi @jonthekiller ,

thank you for reporting this bug. Yesterday, we fixed this bug by making the plugin compatible with newer PHP and Symfony versions in #26 . The fix was released in version [1.2.3](https://github.com/auxmoney/OpentracingBundle-Monolog/releases/tag/v1.2.3), so please update your dependencies.
